### ISSUE TITLE
fix: update the title and favicon for the website

### ISSUE THREAD

**Issue by susanhsrestha** [Seven-Musketeers/frontend#26]
## Describe the bug

The favicon and title could be more appropriate and meaningful.

## Screenshots

![image](https://github.com/Seven-Musketeers/frontend/assets/58846347/8480ce95-22f9-4974-a961-334b062f57a4)

**Comment by thenishantsapkota** [comment]
We're in the development process and currently not accepting any external PRs though. Thank you for the issue
