### ISSUE TITLE
Login and Signup Validation

### ISSUE THREAD

**Issue by Br9ha20** [Seven-Musketeers/frontend#32]

**Comment by purnasth** [comment]
Form validation should be performed on the backend; performing it on the frontend cannot be considered secure.

**Comment by thenishantsapkota** [comment]
The validation is already performed on the backend. No need for login and signup validation on the FE.

**Comment by purnasth** [comment]
@Br9ha20 you can close this issue.

**Comment by Br9ha20** [comment]
Issue Closed.
